# Generated by Django 3.2.9 on 2022-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0002_clientprofile_coachprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('address', models.CharField(max_length=124)),
                ('address_2', models.CharField(blank=True, default='', max_length=124)),
                ('city', models.CharField(max_length=124)),
                ('country', models.CharField(max_length=124)),
                ('postal_code', models.CharField(max_length=64)),
            ],
        ),
    ]
